name: CMake

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  ULTRASCHALL_BUILD_TYPE: Release
  ULTRASCHALL_BUILD_TARGET: reaper_ultraschall

jobs:
  before_build:
    runs-on: ubuntu-latest
    outputs:
      build_timestamp: ${{steps.timestamp.outputs.timestamp}}
      build_id: R5.1_${{github.run_number}}_${{steps.timestamp.outputs.timestamp}}
    steps:
      - name: Create build timestamp
        id: timestamp
        run: echo "::set-output name=timestamp::$(date -u +'%Y%m%d%H%M')"
      - name: Display build timestqmp
        env:
          ULTRASCHALL_BUILD_TIMESTAMP0: "${{steps.timestamp.outputs.timestamp}}"
          ULTRASCHALL_BUILD_ID0: "R5.1_${{github.run_number}}_${{steps.timestamp.outputs.timestamp}}"
        run: |
          echo $ULTRASCHALL_BUILD_TIMESTAMP0
          echo $ULTRASCHALL_BUILD_ID0
          echo $REPO_OWNER
          echo $GITHUB_TOKEN

  build:
    needs: before_build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: setup
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: configure
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -Wno-dev -DCMAKE_BUILD_TYPE=$ULTRASCHALL_BUILD_TYPE
      - name: build
        working-directory: ${{runner.workspace}}/build
        run: cmake --build . --target $ULTRASCHALL_BUILD_TARGET --config $ULTRASCHALL_BUILD_TYPE
      - uses: actions/upload-artifact@v2
        with:
          name: build-artifacts-${{ matrix.os }}
          path: ${{runner.workspace}}/build/src/reaper_ultraschall.*

  after_build:
    needs: [before_build, build]
    runs-on: ubuntu-latest
    steps:
      - name: Create build tag
        env:
          ULTRASCHALL_BUILD_TIMESTAMP1: "${{needs.before_build.outputs.build_timestamp}}"
          ULTRASCHALL_BUILD_ID1: "${{needs.before_build.outputs.build_id}}"
        run: |
          echo $ULTRASCHALL_BUILD_TIMESTAMP1
          echo $ULTRASCHALL_BUILD_ID1
