name: CMake

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  ULTRASCHALL_BUILD_TYPE: Release
  ULTRASCHALL_BUILD_TARGET: reaper_ultraschall

jobs:
  before_build:
    runs-on: ubuntu-latest
    outputs:
      build_timestamp: ${{steps.timestamp.outputs.timestamp}}
      build_id: R5.1_${{github.run_number}}_${{steps.timestamp.outputs.timestamp}}
    steps:
      - name: Create build timestamp
        id: timestamp
        run: echo "::set-output name=timestmap::$(date -u +'%Y%m%d%H%M')"

  build:
    needs: before_build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: Configure
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -Wno-dev -DCMAKE_BUILD_TYPE=$ULTRASCHALL_BUILD_TYPE
      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --target $ULTRASCHALL_BUILD_TARGET --config $ULTRASCHALL_BUILD_TYPE

  after_build:
    needs: [before_build, build]
    runs-on: ubuntu-latest
    steps:
      - name: Create build tag
        env:
          ULTRASCHALL_BUILD_ID: ${{needs.before_build.outputs.build_id}}
        run: |
          echo $ULTRASCHALL_BUILD_ID
