name: CMake

# on: [push, pull_request]
on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  BUILD_TYPE: Release
  BUILD_TARGET: reaper_ultraschall

jobs:
  linux:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake -G"Unix Makefiles" $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --target $BUILD_TARGET --config $BUILD_TYPE

  macos:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: zsh
        working-directory: ${{runner.workspace}}/build
        run: $GITHUB_WORKSPACE cmake -G"Xcode" -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --target $BUILD_TARGET --config $BUILD_TYPE

  win32:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        shell: pwsh
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -G"Visual Studio 16 2019" -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --target $BUILD_TARGET --config $BUILD_TYPE
