name: CMake

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

env:
  ULTRASCHALL_BUILD_ID: ${{github.run_id}}
  ULTRASCHALL_BUILD_TYPE: Release
  ULTRASCHALL_BUILD_TARGET: reaper_ultraschall

jobs:
  before_build:
    runs-on: ubuntu-latest
    steps:
      - name: Create build no
        id: timestamp
        run: echo "::set-output name=timestmap::$(date +'%+4Y%m%d%H%N')"
      - name: Display build no
        run: |
          echo $ULTRASCHALL_BUILD_ID
          echo $ULTRASCHALL_BUILD_NO
        env:
          ULTRASCHALL_BUILD_ID: R5.1_${{github.run_id}}_${{steps.timestamp.outputs.timestmap}}
          ULTRASCHALL_BUILD_NO: R5.1_${{github.run_number}}_${{steps.timestamp.outputs.timestmap}}

  build:
    needs: before_build
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build
      - name: Configure
        shell: bash
        working-directory: ${{runner.workspace}}/build
        run: cmake $GITHUB_WORKSPACE -Wno-dev -DCMAKE_BUILD_TYPE=$ULTRASCHALL_BUILD_TYPE
      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --target $ULTRASCHALL_BUILD_TARGET --config $ULTRASCHALL_BUILD_TYPE

  after_build:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Create build tag
        shell: bash
        working-directory: ${{runner.workspace}}
        run: |
          export ULTRASCHALL_BUILD_DATE="202109041500"
          export ULTRASCHALL_BUILD_NO="R5.1_$GITHUB_RUN_ID_$ULTRASCHALL_BUILD_DATE"
          echo "Release $ULTRASCHALL_BUILD_NO"
